on:
  release:
    types: [published]
  workflow_dispatch:
name: Deploy website on release
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Transfer files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.FTP_SERVER }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "."
        dist_target_dir: "."
        delete: "false"
        exclude: "'^README.md' '^.gitignore' '^admin/config.php' '^LICENSE' '^.git/' '^.github/'"
